/**
 * Convierte un código ISO de país a emoji Unicode de bandera.
 */
function isoToFlagEmoji(isoCode: string): string {
  return isoCode
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
}

/**
 * Mapea nombre de país (MAYÚSCULAS) a código ISO.
 */
const COUNTRY_NAME_TO_ISO: Record<string, string> = {
  AFGHANISTAN: 'AF',
  ALBANIA: 'AL',
  ARGELIA: 'DZ',
  ARGENTINA: 'AR',
  ARMENIA: 'AM',
  AUSTRALIA: 'AU',
  AUSTRIA: 'AT',
  AZERBAIYAN: 'AZ',
  BAHAMAS: 'BS',
  BANGLADESH: 'BD',
  BARBADOS: 'BB',
  BELGICA: 'BE',
  BELICE: 'BZ',
  BENIN: 'BJ',
  BIELORRUSIA: 'BY',
  BOLIVIA: 'BO',
  BOSNIA: 'BA',
  BOTSWANA: 'BW',
  BRASIL: 'BR',
  BULGARIA: 'BG',
  'BURKINA FASO': 'BF',
  BURUNDI: 'BI',
  BUTAN: 'BT',
  'CABO VERDE': 'CV',
  CAMBOYA: 'KH',
  CAMERUN: 'CM',
  CANADA: 'CA',
  CATAR: 'QA',
  CHAD: 'TD',
  CHILE: 'CL',
  CHINA: 'CN',
  CHIPRE: 'CY',
  COLOMBIA: 'CO',
  COMORAS: 'KM',
  CONGO: 'CG',
  'COREA DEL SUR': 'KR',
  'COREA DEL NORTE': 'KP',
  'COSTA DE MARFIL': 'CI',
  'COSTA RICA': 'CR',
  CROACIA: 'HR',
  CUBA: 'CU',
  DINAMARCA: 'DK',
  DOMINICA: 'DM',
  DOMINICANA: 'DO',
  ECUADOR: 'EC',
  EGIPTO: 'EG',
  'EL SALVADOR': 'SV',
  'EMIRATOS ARABES': 'AE',
  ERITREA: 'ER',
  ESLOVAQUIA: 'SK',
  ESLOVENIA: 'SI',
  ESPAÑA: 'ES',
  'ESTADOS UNIDOS': 'US',
  ESTONIA: 'EE',
  ETIOPIA: 'ET',
  FILIPINAS: 'PH',
  FINLANDIA: 'FI',
  FRANCIA: 'FR',
  GABON: 'GA',
  GAMBIA: 'GM',
  GEORGIA: 'GE',
  GHANA: 'GH',
  GRECIA: 'GR',
  GRANADA: 'GD',
  GUATEMALA: 'GT',
  GUINEA: 'GN',
  'GUINEA ECUATORIAL': 'GQ',
  'GUINEA BISSAU': 'GW',
  GUYANA: 'GY',
  HAITI: 'HT',
  HONDURAS: 'HN',
  HUNGRIA: 'HU',
  INDIA: 'IN',
  INDONESIA: 'ID',
  IRAK: 'IQ',
  IRAN: 'IR',
  IRLANDA: 'IE',
  ISLANDIA: 'IS',
  ISRAEL: 'IL',
  ITALIA: 'IT',
  JAMAICA: 'JM',
  JAPON: 'JP',
  JORDANIA: 'JO',
  KAZAJISTAN: 'KZ',
  KENIA: 'KE',
  KIRGUISTAN: 'KG',
  KIRIBATI: 'KI',
  KUWAIT: 'KW',
  LAOS: 'LA',
  LESOTHO: 'LS',
  LETONIA: 'LV',
  LIBANO: 'LB',
  LIBERIA: 'LR',
  LIBIA: 'LY',
  LIECHTENSTEIN: 'LI',
  LITUANIA: 'LT',
  LUXEMBURGO: 'LU',
  MADAGASCAR: 'MG',
  MALASIA: 'MY',
  MALAWI: 'MW',
  MALDIVAS: 'MV',
  MALI: 'ML',
  MALTA: 'MT',
  MARRUECOS: 'MA',
  MARSHALL: 'MH',
  MAURICIO: 'MU',
  MAURITANIA: 'MR',
  MEXICO: 'MX',
  MICRONESIA: 'FM',
  MOLDAVIA: 'MD',
  MONACO: 'MC',
  MONGOLIA: 'MN',
  MONTENEGRO: 'ME',
  MOZAMBIQUE: 'MZ',
  NAMIBIA: 'NA',
  NAURU: 'NR',
  NEPAL: 'NP',
  NICARAGUA: 'NI',
  NIGER: 'NE',
  NIGERIA: 'NG',
  NORUEGA: 'NO',
  'NUEVA ZELANDA': 'NZ',
  OMAN: 'OM',
  PAKISTAN: 'PK',
  PALAU: 'PW',
  PALESTINA: 'PS',
  PANAMA: 'PA',
  'PAPUA NUEVA GUINEA': 'PG',
  PARAGUAY: 'PY',
  'PAIS BAJOS': 'NL',
  PERU: 'PE',
  POLONIA: 'PL',
  PORTUGAL: 'PT',
  'PUERTO RICO': 'PR',
  'REINO UNIDO': 'GB',
  'REPUBLICA CENTROAFRICANA': 'CF',
  'REPUBLICA CHECA': 'CZ',
  'REPUBLICA DEMOCRATICA DEL CONGO': 'CD',
  'REPUBLICA DOMINICANA': 'DO',
  'REPUBLICA ESLOVACA': 'SK',
  'REPUBLICA MOLDAVA': 'MD',
  'REPUBLICA SUDAFRICANA': 'ZA',
  RUANDA: 'RW',
  RUMANIA: 'RO',
  RUSIA: 'RU',
  SAMOA: 'WS',
  'SAN CRISTOBAL Y NIEVES': 'KN',
  'SAN MARINO': 'SM',
  'SAN VICENTE Y LAS GRANADINAS': 'VC',
  'SANTA LUCIA': 'LC',
  'SANTO TOMÉ Y PRÍNCIPE': 'ST',
  SENEGAL: 'SN',
  SERBIA: 'RS',
  SEYCHELLES: 'SC',
  'SIERRA LEONA': 'SL',
  SINGAPUR: 'SG',
  SIRIA: 'SY',
  SOMALIA: 'SO',
  'SRI LANKA': 'LK',
  SUDAFRICA: 'ZA',
  SUDAN: 'SD',
  SUECIA: 'SE',
  SUIZA: 'CH',
  SURINAM: 'SR',
  SWAZILANDIA: 'SZ',
  TAILANDIA: 'TH',
  TANZANIA: 'TZ',
  'TIMOR ORIENTAL': 'TL',
  TOGO: 'TG',
  TONGA: 'TO',
  'TRINIDAD Y TOBAGO': 'TT',
  TUNEZ: 'TN',
  TURKMENISTAN: 'TM',
  TURQUIA: 'TR',
  TUVALU: 'TV',
  UCRANIA: 'UA',
  UGANDA: 'UG',
  URUGUAY: 'UY',
  UZBEKISTAN: 'UZ',
  VATICANO: 'VA',
  VENEZUELA: 'VE',
  VIETNAM: 'VN',
  YEMEN: 'YE',
  YIBUTI: 'DJ',
  ZAMBIA: 'ZM',
  ZIMBABUE: 'ZW',
};

/**
 * Devuelve el emoji de bandera para un rol de país (en mayúsculas).
 * Si no es un país conocido, retorna el nombre original.
 */
export function getCountryFlag(roleName: string): string {
  const iso = COUNTRY_NAME_TO_ISO[roleName.toUpperCase()];
  return iso ? isoToFlagEmoji(iso) : roleName;
}
